services:
  adguardhome:
    image: "adguard/adguardhome:v0.107.71"
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    networks:
      - traefik_proxy
      - dns
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguardhome.entrypoints=web,websecure"
      - "traefik.http.routers.adguardhome.rule=Host(`dns.pi.m1xxos.tech`)"
      - "traefik.http.routers.adguardhome.tls=true"
      - "traefik.http.routers.adguardhome.tls.certresolver=based"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
  dnsproxy:
    image: "adguard/dnsproxy:v0.78.2"
    container_name: dnsproxy
    restart: unless-stopped
    expose:
      - 53/udp
      - 53/tcp
    networks:
      - dns
    environment:
      HTTP_PROXY: http://192.168.1.77:1080
      HTTPS_PROXY: http://192.168.1.77:1080
    command: >
      --upstream https://cloudflare-dns.com/dns-query
      --fallback 8.8.8.8
      --cache

networks:
  traefik_proxy:
    external: true
  dns:
