services:
  adguardhome:
    image: "adguard/adguardhome:v0.107.71"
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    networks:
      - traefik_proxy
      - dns
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguardhome.entrypoints=web,websecure"
      - "traefik.http.routers.adguardhome.rule=Host(`dns.pi.m1xxos.tech`)"
      - "traefik.http.routers.adguardhome.tls=true"
      - "traefik.http.routers.adguardhome.tls.certresolver=based"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"

  nginx-stream:
    image: "nginx:latest"
    container_name: nginx-stream
    restart: unless-stopped
    environment:
      HTTP_PROXY: http://192.168.1.77:1080
      HTTPS_PROXY: http://192.168.1.77:1080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - traefik_proxy
      - dns
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.nginx-stream.entrypoints=websecure"
      - "traefik.tcp.routers.nginx-stream.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.nginx-stream.tls=true"
      - "traefik.tcp.routers.nginx-stream.tls.passthrough=true"
      - "traefik.tcp.services.nginx-stream.loadbalancer.server.port=443"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
    external: true
  dns:
