services:
  adguardhome:
    image: "adguard/adguardhome:v0.107.71"
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    networks:
      - traefik_proxy
      - dns
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguardhome.entrypoints=web,websecure"
      - "traefik.http.routers.adguardhome.rule=Host(`dns.pi.m1xxos.tech`)"
      - "traefik.http.routers.adguardhome.tls=true"
      - "traefik.http.routers.adguardhome.tls.certresolver=based"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"

  sni-proxy:
    image: "traefik:v3.3"
    container_name: sni-proxy
    restart: unless-stopped
    environment:
      HTTP_PROXY: http://192.168.1.77:1080
      HTTPS_PROXY: http://192.168.1.77:1080
    volumes:
      - ./traefik-stream.yaml:/etc/traefik/traefik.yaml:ro
      - ./dynamic.yaml:/etc/traefik/dynamic.yaml:ro
    networks:
      - traefik_proxy
      - dns
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.sni-proxy.entrypoints=websecure"
      - "traefik.tcp.routers.sni-proxy.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sni-proxy.tls.passthrough=true"
      - "traefik.tcp.services.sni-proxy.loadbalancer.server.port=443"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
    external: true
  dns:
